# Generated by Django 4.2.30 on 2026-10-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0002_usuario_ciudad_usuario_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcontrato',
            name='garantia_cobrada',
        ),
        migrations.RemoveField(
            model_name='itemcontrato',
            name='precio_diario_cobrado',
        ),
        migrations.AddField(
            model_name='itemcarro',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='itemcarro',
            name='costo_delivery',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='itemcarro',
            name='factor_uso',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='itemcontrato',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='itemcontrato',
            name='precio_cobrado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='maquinaria',
            name='imagen_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='maquinaria',
            name='tipo',
            field=models.CharField(choices=[('MAQUINARIA', 'Maquinaria Pesada'), ('MATERIAL', 'Material de Construcción')], default='MAQUINARIA', max_length=20),
        ),
        migrations.AlterField(
            model_name='itemcarro',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemcarro',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemcontrato',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemcontrato',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='garantia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='stock_disponible',
            field=models.IntegerField(default=1),
        ),
    ]
