# Generated by Django 4.2.30 on 2026-10-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0003_remove_itemcontrato_garantia_cobrada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('nombre_encargado', models.CharField(max_length=150)),
                ('titulo_universitario', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=20)),
                ('horario', models.CharField(max_length=100)),
                ('foto_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
