# Generated by Django 4.2.30 on 2026-10-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0004_servicioexterno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_url', models.URLField(blank=True, max_length=500, null=True)),
                ('titulo_banner', models.CharField(default='Espacio para Banner E-Commerce', max_length=200)),
            ],
        ),
    ]
