# Generated by Django 4.2.30 on 2026-10-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0005_configuracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='subtitulo_principal',
            field=models.TextField(default='Maquinarias de última generación, asesorías y materiales minoristas y mayoristas.'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='titulo_principal',
            field=models.CharField(default='Renta testa.', max_length=200),
        ),
    ]
