# Generated by Django 4.2.30 on 2026-10-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0006_configuracion_subtitulo_principal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinaria',
            name='descripcion_detallada',
            field=models.TextField(blank=True, null=True),
        ),
    ]
