# Generated by Django 4.2.30 on 2026-10-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0007_maquinaria_descripcion_detallada'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinaria',
            name='imagen_upload',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AddField(
            model_name='servicioexterno',
            name='foto_upload',
            field=models.ImageField(blank=True, null=True, upload_to='servicios/'),
        ),
    ]
